name: nekoshare

services:
    database:
        image: mysql:8.4.6
        restart: always
        env_file:
            - .env
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - nekoshare-net
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s
            retries: 5

volumes:
    mysql-data:

networks:
    nekoshare-net:
        driver: bridge
        name: nekoshare-net
        driver_opts:
            com.docker.network.bridge.enable_ip_masquerade: "true"
